### ISSUE TITLE
Error when following *args or **kwargs with a comma

### ISSUE THREAD

**Issue by danielknell** [google/yapf#532]
When you try and run yapf on code with an asterisk in the param definition, and a comma at the end of the last item (to force multiline) it raises an exception.

```pytb
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/yapf/yapflib/pytree_utils.py", line 103, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/usr/local/lib/python3.6/lib2to3/pgen2/driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/usr/local/lib/python3.6/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/usr/local/lib/python3.6/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=12, value=',', context=('', (1, 18))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/yapf/yapflib/yapf_api.py", line 128, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/usr/local/lib/python3.6/site-packages/yapf/yapflib/pytree_utils.py", line 109, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/usr/local/lib/python3.6/lib2to3/pgen2/driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/usr/local/lib/python3.6/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/usr/local/lib/python3.6/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=12, value=',', context=('', (1, 18))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yapf", line 11, in <module>
    sys.exit(run_main())
  File "/usr/local/lib/python3.6/site-packages/yapf/__init__.py", line 312, in run_main
    sys.exit(main(sys.argv))
  File "/usr/local/lib/python3.6/site-packages/yapf/__init__.py", line 182, in main
    verify=args.verify)
  File "/usr/local/lib/python3.6/site-packages/yapf/yapflib/yapf_api.py", line 130, in FormatCode
    raise parse.ParseError(filename + ': ' + e.message)
AttributeError: 'ParseError' object has no attribute 'message'
```

I can trigger it from following minimal examples:

position arguments
```sh
echo "def foo(bar, *baz,): pass" | yapf --no-local-style
```
keyword arguments
```sh
echo "def foo(bar, **baz): pass" | yapf --no-local-style
```
keyword-only argument
```sh
echo "def foo(bar, *, baz,): pass" | yapf --no-local-style
```

In all cases removing the last comma allows yapf to format the code without errors.

```
$ python --version
Python 3.6.4
$ yapf --version
yapf 0.20.2
```

**Comment by gwelymernans** [comment]
The failure is coming from lib2to3, which we have no control over.

**Comment by kamahen** [comment]
These examples only work with Python 3.6. And it appears that lib2to3/Grammar.txt isn't compatible with them (lib2to3/Grammar.txt does have the changes for variable type annotations, AFAICT).

**Comment by kamahen** [comment]
https://bugs.python.org/issue33064 ... so it should be fixed in the next Python 3.6.x release.
