### ISSUE TITLE
Trailing comma in function definition in combination with * crashes

### ISSUE THREAD

**Issue by cjgu** [google/yapf#494]
Using * and trailing comma in function definition crashes yapf under Python 3.6.1. Traces looks very similar to other errors caused by lib2to3 incompabilites.

Reproduce with
```
$ cat repro.py
def a(b, *, c,):
    pass
```

Yields error:
```
 $ yapf repro.py
Traceback (most recent call last):
  File "/Users/xxx/lib/python3.6/site-packages/yapf/yapflib/pytree_utils.py", line 103, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib2to3/pgen2/driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=8, value=')', context=('', (2, 14))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xxx/lib/python3.6/site-packages/yapf/yapflib/yapf_api.py", line 128, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/Users/xxx/lib/python3.6/site-packages/yapf/yapflib/pytree_utils.py", line 109, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib2to3/pgen2/driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=8, value=')', context=('', (2, 14))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xxx/bin/yapf", line 11, in <module>
    sys.exit(run_main())
  File "/Users/xx/lib/python3.6/site-packages/yapf/__init__.py", line 308, in run_main
    sys.exit(main(sys.argv))
  File "/Users/xxx/lib/python3.6/site-packages/yapf/__init__.py", line 196, in main
    verbose=args.verbose)
  File "/Users/xxx/lib/python3.6/site-packages/yapf/__init__.py", line 246, in FormatFiles
    in_place, print_diff, verify, verbose)
  File "/Users/xxx/lib/python3.6/site-packages/yapf/__init__.py", line 271, in _FormatFile
    logger=logging.warning)
  File "/Users/xxx/lib/python3.6/site-packages/yapf/yapflib/yapf_api.py", line 90, in FormatFile
    verify=verify)
  File "/Users/xxx/lib/python3.6/site-packages/yapf/yapflib/yapf_api.py", line 130, in FormatCode
    raise parse.ParseError(filename + ': ' + e.message)
AttributeError: 'ParseError' object has no attribute 'message'
```

**Comment by cjgu** [comment]
This is fixed by using a newer python 3.6 (e.g 3.6.4).

**Comment by dhoffman34** [comment]
I am still seeing this with Python 3.6.4 and the latest version of yapf:

```
dhoffman:tmp dhoffman$ cat repro.py
def a(b, *, c,):
    pass
dhoffman:tmp dhoffman$ PYTHONPATH=yapf python3.6 yapf/yapf repro.py
Traceback (most recent call last):
  File "/Users/dhoffman/tmp/yapf/yapf/yapflib/pytree_utils.py", line 103, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib2to3/pgen2/driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=8, value=')', context=('', (1, 14))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dhoffman/tmp/yapf/yapf/yapflib/yapf_api.py", line 128, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/Users/dhoffman/tmp/yapf/yapf/yapflib/pytree_utils.py", line 109, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib2to3/pgen2/driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=8, value=')', context=('', (1, 14))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "yapf/yapf/__main__.py", line 18, in <module>
    yapf.run_main()
  File "/Users/dhoffman/tmp/yapf/yapf/__init__.py", line 312, in run_main
    sys.exit(main(sys.argv))
  File "/Users/dhoffman/tmp/yapf/yapf/__init__.py", line 200, in main
    verbose=args.verbose)
  File "/Users/dhoffman/tmp/yapf/yapf/__init__.py", line 250, in FormatFiles
    in_place, print_diff, verify, verbose)
  File "/Users/dhoffman/tmp/yapf/yapf/__init__.py", line 275, in _FormatFile
    logger=logging.warning)
  File "/Users/dhoffman/tmp/yapf/yapf/yapflib/yapf_api.py", line 90, in FormatFile
    verify=verify)
  File "/Users/dhoffman/tmp/yapf/yapf/yapflib/yapf_api.py", line 130, in FormatCode
    raise parse.ParseError(filename + ': ' + e.message)
AttributeError: 'ParseError' object has no attribute 'message'
dhoffman:tmp dhoffman$ python3.6 --version
Python 3.6.4
```

**Comment by Alok** [comment]
This is now fixed with the release of 3.6.5. I just tested it.

**Comment by dhoffman34** [comment]
I have also verified that this is working with 3.6.5.

**Comment by Alok** [comment]
I think this can be closed then.
